### ISSUE TITLE
CUDA kernel failed : no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by reem-codes** [erikwijmans/Pointnet2_PyTorch#158]
Hello, I'm facing this error while running the code:
```
CUDA kernel failed : no kernel image is available for execution on the device
void furthest_point_sampling_kernel_wrapper(int, int, int, const float*, float*, int*) at L...
```

from conda:
```
pytorch                   1.4.0           py3.6_cuda10.0.130_cudnn7.6.3_0    pytorch
cudatoolkit               10.0.130             hf841e97_9    conda-forge
```
nvcc version:
```
Cuda compilation tools, release 10.0, V10.0.130
```
nvidia-smi version
```
CUDA Version: 11.3 
```

I have another pytorch program running in the same environment and it's working, this trivial example to show it running
```
>>> import torch
>>> torch.version.cuda
'10.0'
>>> torch.__version__
'1.4.0'
>>> torch.cuda.is_available()
True
>>> device = torch.device('cuda')
>>> a = torch.zeros(5)
>>> a.to(device)
tensor([0., 0., 0., 0., 0.], device='cuda:0')
```

**Comment by reem-codes** [comment]
I solved it by updating cuda + pytorch:

```
cudatoolkit               10.2.89              hfd86e86_1  
pytorch                   1.9.1           py3.6_cuda10.2_cudnn7.6.5_0    pytorch
```

and of course, using nvcc of cuda 10.2.89

**Comment by HansRen1024** [comment]
here is a new solution without botherring the cuda version:
https://github.com/mkt1412/GraspGPT_public/issues/8
