### ISSUE TITLE
Error when importing pointnet2_utils

### ISSUE THREAD

**Issue by ardianumam** [erikwijmans/Pointnet2_PyTorch#175]
Hi,

Thanks for the great work! I try to run the code, and get this error:
```CUDA error: the provided PTX was compiled with an unsupported toolchain.```

This error only happens when I import as ```from pointnet2_ops import pointnet2_utils``` (commenting related to this code has no error). And the error also only happens when I use Nvidia Ampere arc, specifically, Nvidia A5000. Here is my other setting:
1. Python: ver 3.9
2. Pytorch: ver 1.9, with cuda 11.1
3. Cuda driver in my Ubuntu machine: 11.3

Note: the installation goes well, without any error message

Thanks!

**Comment by ardianumam** [comment]
Thanks to this PyTorch forum [here](https://discuss.pytorch.org/t/cuda-error-the-provided-ptx-was-compiled-with-an-unsupported-toolchain-in-nvidia-ampere/187236), I added “8.6” in the TORCH_CUDA_ARCH_LIST [here](https://github.com/erikwijmans/Pointnet2_PyTorch/blob/b5ceb6d9ca0467ea34beb81023f96ee82228f626/pointnet2_ops_lib/setup.py#L19), and it solved the issue.
