### ISSUE TITLE
CUDA kernel failed : an illegal memory access was encountered

### ISSUE THREAD

**Issue by Rubikplayer** [erikwijmans/Pointnet2_PyTorch#73]
Hi, thanks for your pytorch implementation on pointnet++. I encountered the following issues, and please let me know if any suggestions. Thanks!!

My code:
```
B = 2
N = 32
inputs = torch.randn(B, N, 6, requires_grad=True ).cuda().float()
labels = torch.from_numpy(np.random.randint(0, 3, size=B * N)).view(B, N).cuda()
model = Pointnet2SemMSG(num_classes=3, input_channels=3, use_xyz=True)
model.cuda()
outputs = model.forward( inputs )
loss_fake = nn.CrossEntropyLoss()( outputs.view(B,3,N), labels )
loss_fake.backward()
print( inputs.grad )
```

Error message:
```
CUDA kernel failed : an illegal memory access was encountered
void three_interpolate_kernel_wrapper(int, int, int, int, const float*, const int*, const float*, float*) at L:110 in pointnet2/_ext-src/src/interpolate_gpu.cu
```

Note: I ran the code with `CUDA_LAUNCH_BLOCKING=1`, this shows the info on `three_interpolate_kernel_wrapper()` as above.

My environments:
 - Python 3.7 on 1080Ti GPU:
 - pytorch:     1.2.0-py3.7_cuda9.2.148_cudnn7.6.2_0
 - torchvision: 0.4.0-py37_cu92

**Comment by erikwijmans** [comment]
`N = 32` is likely the issue.   Try `N >= 1024` or change the number of points the subsampling layers subsample to to be less than 32.

**Comment by Rubikplayer** [comment]
Thanks for the feedback, @erikwijmans! Issue solved.
